2019-12-13 18:41:09 WARN  CustomersDAOImpl:98 - Unable to update customer information
org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:127)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1018)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:348)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:335)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:84)
	at com.revature.models.Bank.existingUserLoginCustomer(Bank.java:146)
	at com.revature.models.Bank.startHere(Bank.java:34)
	at com.revature.Driver.main(Driver.java:32)
2019-12-13 18:42:19 WARN  CustomersDAOImpl:98 - Unable to update customer information
org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:127)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1018)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:348)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:335)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:84)
	at com.revature.models.Bank.existingUserLoginCustomer(Bank.java:146)
	at com.revature.models.Bank.startHere(Bank.java:34)
	at com.revature.Driver.main(Driver.java:32)
2019-12-13 18:48:57 WARN  ConnectionUtil:24 - Unable to obtain connection to database
org.postgresql.util.PSQLException: FATAL: database "project0" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2617)
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:135)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:250)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:22)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:80)
	at com.revature.models.Bank.existingUserLoginCustomer(Bank.java:146)
	at com.revature.models.Bank.startHere(Bank.java:34)
	at com.revature.Driver.main(Driver.java:32)
2019-12-13 18:53:51 WARN  ConnectionUtil:24 - Unable to obtain connection to database
org.postgresql.util.PSQLException: FATAL: database "project0" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2617)
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:135)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:250)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:22)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:80)
	at com.revature.models.Bank.existingUserLoginCustomer(Bank.java:146)
	at com.revature.models.Bank.startHere(Bank.java:34)
	at com.revature.Driver.main(Driver.java:32)
2019-12-13 18:54:13 WARN  CustomersDAOImpl:98 - Unable to update customer information
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.models.Bank.existingUserLoginCustomer(Bank.java:146)
	at com.revature.models.Bank.startHere(Bank.java:34)
	at com.revature.Driver.main(Driver.java:32)
2019-12-13 18:59:32 WARN  CustomersDAOImpl:98 - Unable to update customer information
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.models.Bank.existingUserLoginCustomer(Bank.java:146)
	at com.revature.models.Bank.startHere(Bank.java:34)
	at com.revature.Driver.main(Driver.java:32)
2019-12-13 19:06:07 WARN  CustomersDAOImpl:98 - Unable to verify if customer exists
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.models.Bank.existingUserLoginCustomer(Bank.java:147)
	at com.revature.models.Bank.startHere(Bank.java:35)
	at com.revature.Driver.main(Driver.java:32)
